<a href="https://colab.research.google.com/github/elenaaalmg/PracticasComputacionII/blob/main/CII_PracticaI_AGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
  Elena Almanza García
  24/02/2022
  elena.almg@gmail.com
'''

import numpy as np

class GaussJordan:
  def pivoteo(self, M, i):
    col = M[i:,i] # se separa una columna de la matriz. todos los renglones a apartir de la diagonal principal, columna i
    numMax = np.argmax(col) #indice del mayor numero que se encuentra en col
    return numMax
  

  def cambioRenglon(self, numMax, aR, M):
    if (numMax != 0):
      tmp = np.copy(M[aR,:]) #copia de un reglon completo de la matriz. reglon actual (aR), todas las columnas
      M[aR,:] = M[numMax + aR,:] #renglon donde se encuentra el indice máximo con todas las columnas
      M[numMax + aR,:] = tmp
      #Recordemos que numMax es el indice del mayor numero que se encuentra en col (variable de la función pivoteo()), col es una sola columna 
      #que se separa a partir de la diagonal principal de la matriz definida, esto significa que el indice original disminuye en 1. Por ejemplo, 
      #tomemos una matriz de 3x3 [[1,2,3],[4,5,6],[7,8,9]], en nuestra segunda iteración, aR = 1 (que se indica en la función eliminacionAdelante()) 
      #nosotros tenemos colOriginal = [2,5,8], OriginalNumMax = 2, col = [5,8], numMax = 1. Es por ello que a numMax se le debe sumar el indice del 
      #renglon actual, para arreglar este desplazamiento y evitar errores en la eliminación
    return M

  
  def restaRenglones(self, k, R1, R2, M):
    M[R2,:] = M[R2,:] - k*M[R1,:] #renglones con todas las columnas
    return M 
  
  
  def eliminacionAdelante(self, M):
    for i in range(len(M) - 1):
      pivote = M[i][i] #elementos de la diagonal principal 
      indiceMax = self.pivoteo(M, i)
      if pivote == 0 or pivote < M[indiceMax + i][i]: #el +i es para corregir el desplazamiento, razón similar a la explicada en la función cambioRenglon()
        M = self.cambioRenglon(indiceMax, i, M)
        pivote = M[i][i] #si se hace el cambio de renglon se debe actualizar el valor del pivote
      
      for j in range(i + 1, len(M)): #el +1 es para que se haga la eliminación debajo del renglon actual
        k = M[j][i] / pivote #factor para hacer ceros debajo de pivote
        M = self.restaRenglones(k,i,j,M)
    print("\nMatriz Gaussiana:\n", M)
    return M

  
  def eliminacionAtras(self, M):
    for i in range(len(M) - 1, -1, -1): #este for itera de forma inversa, es decir, apartir del último indice de la matriz hacia arriba con incrementos de -1
      pivote = M[i][i]
      if pivote == 0: #el pivote del ultimo renglon de la matriz no puede ser cero 
        print("\nEl sistema no tiene solución")
        exit(0)
      else:
        for j in range(i - 1, -1, -1): #el -1 es para que la eliminación se haga por encima del renglon actual
          k = M[j][i] / pivote #para hacer ceros arriba del pivote
          M = self.restaRenglones(k,i,j,M)
    print("\nMatriz Jordan:\n", M)
    return M
  
   
  def diagonalUnos(self, M):
    #a pesar de tya haber hecho la eliminación hacia adelante y hacia atras, los pivotes aún no son unos; el próposito de esta 
    #función es generar la matriz escalonada reducida haciendo la diagonal de unos 
    for i in range(len(M)):
      M[i,:] = M[i,:] / M[i][i] #renglon actual con todas las columnas divido del pivote
    print("\nMatriz escalonada reducida:\n", M)
    return M


def llenarMatriz(M, R, c):
  #Le pedimos al usuario que llene la matriz aumentada
  print("\nPor favor ingrese la matriz aumentanda del sistema:")
  for i in range(R):
    for j in range(c):
      M[i][j] = (input("Valor del elemento [" + str(i) + "][" + str(j) + "] : "))
      M = np.array(M, dtype = float)
  print("\nMatriz aumentada:\n", M)
  return M

  
def imprimirSol(M, ultimaCol):
  x = np.copy(M[:,ultimaCol]) #Matriz con todos los renglones pero solo la última columna
  print("\nSolución:")
  for i in range(len(x)):
    print("x",i+1,": ",x[i])
  return x


def main():
  #Definimos el numero de renglones y columnas
  ecuaciones = int(input("Inserte en número de ecuaciones: ")) 
  R = ecuaciones #el numero de ecuaciones equivale al numero de renglones
  c = R + 1 #el +1 es por la columna de resultados

  M = np.zeros((R,c))
  M = llenarMatriz(M, R, c)

  #creación de objeto
  objGJ = GaussJordan()
  M = objGJ.eliminacionAdelante(M)
  M = objGJ.eliminacionAtras(M)
  M = objGJ.diagonalUnos(M)
  sol = imprimirSol(M,len(M[0])-1) #len((M[0])-1) hace refenrencia a la ultima columna de la matriz (la matriz de resultados)


if __name__ == "__main__":
    main()

Inserte en número de ecuaciones: 2

Por favor ingrese la matriz aumentanda del sistema:
Valor del elemento [0][0] : 4
Valor del elemento [0][1] : 5
Valor del elemento [0][2] : 6
Valor del elemento [1][0] : 7
Valor del elemento [1][1] : 8
Valor del elemento [1][2] : 9

Matriz aumentada:
 [[4. 5. 6.]
 [7. 8. 9.]]

Matriz Gaussiana:
 [[7.         8.         9.        ]
 [0.         0.42857143 0.85714286]]

Matriz Jordan:
 [[ 7.          0.         -7.        ]
 [ 0.          0.42857143  0.85714286]]

Matriz escalonada reducida:
 [[ 1.  0. -1.]
 [ 0.  1.  2.]]

Solución:
x 1 :  [-1.]
x 2 :  [2.]
